builds:
  - binary: go-cli-tools
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLE=0
    flags:
      - -mod=vendor
release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  - 
    name: go-cli-tools
    homepage: https://github.com/louispham22/go-cli-tools
    tap:
      owner: louispham22
      name: homebrew-go-cli-tools
    commit_author:
      name: louispham22
      email: tungpv.it@gmail.com

checksum:
  name_template: 'checksums.txt'
      